<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-L3U3DAD" failures="1" tests="10" name="Default test" time="56.045" errors="0" timestamp="2025-06-12T15:05:08 GMT+03:00">
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="VerifyHomepageLoadsSuccessfully" time="0.196"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="VerifyCategoryNavigation" time="7.233"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="VerifySearchResultsAccuracy" time="4.485"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="productDetailPageAccuracy" time="2.543"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="addToTheCart" time="12.801"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="ShoppingCartReview" time="4.029"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="PromotionsPageAccessibility" time="2.271"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="ContactInformationAvailability" time="0.285"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="UserRegistrationProcess" time="6.696">
    <failure type="java.lang.AssertionError" message="confirmation Message not appeared expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: confirmation Message not appeared expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at SmartBuyProject.SmartBuyProject.AppTest.UserRegistrationProcess(AppTest.java:237)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- UserRegistrationProcess -->
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="UserLoginFunctionality" time="4.365"/>
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="RemoveItemsfromCart" time="0.0">
    <ignored/>
  </testcase> <!-- RemoveItemsfromCart -->
  <testcase classname="SmartBuyProject.SmartBuyProject.AppTest" name="UpdateCartQuantities" time="0.0">
    <ignored/>
  </testcase> <!-- UpdateCartQuantities -->
</testsuite> <!-- Default test -->
